name: 뉴스 자동 모니터링

on:
  workflow_dispatch:  # 수동 실행 가능
  schedule:
    - cron: "*/30 * * * *"  # 매시간 정각 실행

jobs:
  make-file:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소에 있는 파일 불러오기
        uses: actions/checkout@v4

      - name: Java 17 세팅
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gson 라이브러리 다운로드
        run: |
          wget https://repo1.maven.org/maven2/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar

      - name: Gson 라이브러리 포함하여 컴파일
        run: |
          javac -cp gson-2.10.1.jar App_news.java Monitoring_news.java SortType.java

      - name: Gson 포함하여 실행
        run: |
          java -cp gson-2.10.1.jar:. App_news
        env:
          KEYWORD: ${{ vars.KEYWORD }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}

      - name: 실행 결과를 Gmail로 전송
        run: |
          echo "뉴스 자동 모니터링 결과 파일을 첨부합니다." | mutt -s "자동 뉴스 모니터링 결과" -a output.txt -- byumm315@gmail.com
        env:
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

      - name: 실행 결과로 나온 파일을 커밋
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "자동 뉴스 모니터링"
          add: "."
